### ISSUE TITLE
queue指令會導致意外中止正在播放中的歌單

### ISSUE THREAD

**Issue by eyes8168** [blackcatbot/blackcat#217]
### 目前行為

重現步驟

1. 使用任意方式將歌單加入機器人播放清單(觸發時使用撥放列表，但我想或許反覆加入多首歌也可以)
2. 使用/queue指令，開啟播放清單
3. 放著不動 或 使用按鈕任意翻頁 或 按下紅色按鈕關閉歌單
4. 即使歌單內還有歌，正在播放的歌曲結束會直接關閉播放清單

### 預期行為

應該繼續播放現在的歌單而不是中止歌單

**Comment by wolf-yuan-6115** [comment]
> ### 目前行為
> 重現步驟
> 
> 1. 使用任意方式將歌單加入機器人播放清單(觸發時使用撥放列表，但我想或許反覆加入多首歌也可以)
> 2. 使用/queue指令，開啟播放清單
> 3. 放著不動 或 使用按鈕任意翻頁 或 按下紅色按鈕關閉歌單
> 4. 即使歌單內還有歌，正在播放的歌曲結束會直接關閉播放清單
> 
> ### 預期行為
> 應該繼續播放現在的歌單而不是中止歌單
> 
> ### 其他細節
> _No response_

感謝回報，稍後會修復程式碼

**Comment by wolf-yuan-6115** [comment]
已修復(https://github.com/blackcatbot/blackcat/commit/9878853c1a4c9de7c1b3f425855f313855780364)，伺服器端會在幾天內更新

**Comment by wolf-yuan-6115** [comment]
伺服器端已更新
