### ISSUE TITLE
如果各位在使用開源版遇到這個問題

### ISSUE THREAD

**Issue by ItJameaplay** [blackcatbot/blackcat#228]
**如果console吐出以下錯誤**
```js
04/09 10:31:52 錯誤 Cannot read properties of undefined (reading 'decoratedPlayerBarRenderer')
04/09 10:31:52 偵錯 TypeError: Cannot read properties of undefined (reading 'decoratedPlayerBarRenderer')
04/09 10:31:52 偵錯     at video_basic_info (/home/jamesliu0224/blackcat/node_modules/play-dl/dist/index.js:2:1522)
04/09 10:31:52 偵錯     at processTicksAndRejections (node:internal/process/task_queues:96:5)
04/09 10:31:52 偵錯     at async Object.video_info (/home/jamesliu0224/blackcat/node_modules/play-dl/dist/index.js:3:1036)
04/09 10:31:52 偵錯     at async Player.play (file:///home/jamesliu0224/blackcat/src/audio/Player.js:198:21)
```
**爲什麼會發生問題**
這個問題是發生在play-dl的套件上
https://github.com/play-dl/play-dl/pull/282
**解決方法**
更新play-dl在console中打入`npm install play-dl -f`就可以更新

使用裝置/系統： Google Compute Engine/Debian GNU/Linux 11 (bullseye) x86_64

**Comment by wolf-yuan-6115** [comment]
> **如果console吐出以下錯誤**
> 
> ```js
> 04/09 10:31:52 錯誤 Cannot read properties of undefined (reading 'decoratedPlayerBarRenderer')
> 04/09 10:31:52 偵錯 TypeError: Cannot read properties of undefined (reading 'decoratedPlayerBarRenderer')
> 04/09 10:31:52 偵錯     at video_basic_info (/home/jamesliu0224/blackcat/node_modules/play-dl/dist/index.js:2:1522)
> 04/09 10:31:52 偵錯     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 04/09 10:31:52 偵錯     at async Object.video_info (/home/jamesliu0224/blackcat/node_modules/play-dl/dist/index.js:3:1036)
> 04/09 10:31:52 偵錯     at async Player.play (file:///home/jamesliu0224/blackcat/src/audio/Player.js:198:21)
> ```
> 
> **爲什麼會發生問題** 這個問題是發生在play-dl的套件上 [play-dl/play-dl#282](https://github.com/play-dl/play-dl/pull/282) **解決方法** 更新play-dl在console中打入`npm install play-dl -f`就可以更新
> 
> 使用裝置/系統： Google Compute Engine/Debian GNU/Linux 11 (bullseye) x86_64

Bro我已經更新了

**Comment by wolf-yuan-6115** [comment]
https://github.com/blackcatbot/blackcat/commit/f22ad58ae0fd7130f86af5653b7094c43ac6aca5
