### ISSUE TITLE
播放會出事

### ISSUE THREAD

**Issue by ItJameaplay** [blackcatbot/blackcat#237]
### 目前行為

![圖片](https://user-images.githubusercontent.com/54131918/167352489-1edac0ca-c734-4caa-b78d-e0b7977c8314.png)
一但嘗試播放機器人就會crash

### 終端輸出

```js

/home/jamesliu0224/blackcat/node_modules/skia-canvas/lib/index.js:570
          onerror(new Error(`Failed to load image from "${src}" (error ${code})`))
                  ^

Error: Failed to load image from "https://i3.ytimg.com/vi/undefined/maxresdefault.jpg" (error 404)
    at /home/jamesliu0224/blackcat/node_modules/skia-canvas/lib/index.js:570:19
    at /home/jamesliu0224/blackcat/node_modules/simple-get/index.js:98:7
    at IncomingMessage.<anonymous> (/home/jamesliu0224/blackcat/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v17.9.0
```

### 使用的軟體套件管理系統

yarn

### 作業系統

Linux (Ubuntu)

### 其他細節

version: 3.0.0
使用系統

**Comment by Gary50613** [comment]
```https://i3.ytimg.com/vi/undefined/maxresdefault.jpg```

the id prameter in the url is undefined, need to check

**Comment by chingh1123** [comment]
fail to load image
說明系統不能過濾到該圖片 owob

**Comment by Gary50613** [comment]
finally I found this line, @wolf-yuan-6115 good luck!

https://github.com/blackcatbot/blackcat/blob/4d544721d7fe892c29cfac6e15172f9644c0562f/src/audio/Player.js#L734

**Comment by wolf-yuan-6115** [comment]
> fail to load image 說明系統不能過濾到該圖片 owob

Fixed

**Comment by wolf-yuan-6115** [comment]
I forget there is another data fetcher in the code
