### ISSUE TITLE
當播放需要年齡認證的歌曲會造成機器人Crash

### ISSUE THREAD

**Issue by eyes8168** [blackcatbot/blackcat#243]
### 目前行為

使用play指令播放這個影片
https://www.youtube.com/watch?v=x8VYWazR5mE

會跳出錯誤訊息如附圖，接著機器人就會停止播放
![image](https://user-images.githubusercontent.com/36183322/168771709-b19fddd5-26ee-4a49-bd12-7217fb501d54.png)
之後如果重新用別的指令啟動機器人就會無法連接
![image](https://user-images.githubusercontent.com/36183322/168772164-59d76168-1784-4dcf-bf95-e95118153921.png)

### 預期行為

應順利完成音樂播放
若無法播放應該也不要讓機器人後續無法使用

### 其他細節

目前初步推測，只要是需要帳號登入進行年齡認證的連結都可能觸發類似問題
另建議提供指令供使用者自行重整機器人狀態，並免當機卡死影響使用

**Comment by wolf-yuan-6115** [comment]
感謝回報，我會繼續了解這個問題

**Comment by eyes8168** [comment]
關閉的原因是短期內暫時無法修復，還是已經修正?

**Comment by wolf-yuan-6115** [comment]
> 關閉的原因是短期內暫時無法修復，還是已經修正?

短期內不會修
