### ISSUE TITLE
無法開啟包含檔案: 'napi.h'

### ISSUE THREAD

**Issue by wibe01204** [blackcatbot/blackcat#303]
### 目前行為

這是在跑 `yarn install` 時發生的錯誤
看了很多文，不過不是本科生不知從何下手
以下是我遇到的問題
感謝!!

### 終端輸出

warning ..\..\..\..\..\..\..\package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ cmake-js build
[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\node_modules\\cmake-js\\bin\\cmake-js',
  'build'
]
info TOOL Using Visual Studio 17 2022 generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  binding.cc
C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\src\binding.cc(1,10): fatal  error C1083: 無法開啟
包含檔案:
'napi.h': No such file or directory [C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\node-libs
amplerate.vcxproj]
  node-libsamplerate.cc
C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\src\./node-libsamplerate.h(1,10): fatal  error C1083
: 無法開啟包含檔案: 'napi.h': No such file or directory [C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\bui
ld\node-libsamplerate.vcxproj]
  正在產生程式碼...
ERR! OMG Process terminated: 1
error Command failed with exit code 1.

### 使用的軟體套件管理系統

npm

### 作業系統

Windows

**Comment by wolf-yuan-6115** [comment]
我沒遇過這種狀況，我會嘗試修復這個問題
修復完成前您可以使用Windows Subsystem For Linux或是直接使用Linux系統編譯

**Comment by wibe01204** [comment]
@wolf-yuan-6115 我改用wsl可以正常啟動了 感謝~
