### ISSUE TITLE
Error: CLUSTERING_READY_DIED | ClusterId: 0

### ISSUE THREAD

**Issue by wibe01204** [blackcatbot/blackcat#304]
### 目前行為

啟動時出現以下報錯
還請指教 感謝!

### 終端輸出

09/19 00:30:52 資訊 成功讀取設定
C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\node_modules\bindings\bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\Debug\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\Release\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\out\Debug\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\Debug\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\out\Release\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\Release\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\default\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\compiled\16.17.0\win32\x64\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\addon-build\release\install-root\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\addon-build\debug\install-root\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\addon-build\default\install-root\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\lib\binding\node-v93-win32-x64\node-libsamplerate.node
    at bindings (C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\index.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24) {
  tries: [
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\Debug\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\Release\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\out\\Debug\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\Debug\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\out\\Release\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\Release\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\default\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\compiled\\16.17.0\\win32\\x64\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\addon-build\\release\\install-root\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\addon-build\\debug\\install-root\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\addon-build\\default\\install-root\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\lib\\binding\\node-v93-win32-x64\\node-libsamplerate.node'
  ]
}
09/19 00:30:54 資訊 成功讀取設定
C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\node_modules\bindings\bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\Debug\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\Release\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\out\Debug\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\Debug\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\out\Release\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\Release\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\build\default\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\compiled\16.17.0\win32\x64\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\addon-build\release\install-root\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\addon-build\debug\install-root\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\addon-build\default\install-root\node-libsamplerate.node
 → C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\lib\binding\node-v93-win32-x64\node-libsamplerate.node
    at bindings (C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\wibe0\OneDrive\桌面\blackcat\src\audio\engine\libsamplerate\index.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24) {
  tries: [
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\Debug\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\Release\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\out\\Debug\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\Debug\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\out\\Release\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\Release\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\build\\default\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\compiled\\16.17.0\\win32\\x64\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\addon-build\\release\\install-root\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\addon-build\\debug\\install-root\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\addon-build\\default\\install-root\\node-libsamplerate.node',
    'C:\\Users\\wibe0\\OneDrive\\桌面\\blackcat\\src\\audio\\engine\\libsamplerate\\lib\\binding\\node-v93-win32-x64\\node-libsamplerate.node'
  ]
}
C:\Users\wibe0\OneDrive\桌面\blackcat\node_modules\discord-hybrid-sharding\src\Core\Cluster.js:154
                reject(new Error('CLUSTERING_READY_DIED | ClusterId: ' + this.id));
                       ^

Error: CLUSTERING_READY_DIED | ClusterId: 0
    at Cluster.onDeath (C:\Users\wibe0\OneDrive\桌面\blackcat\node_modules\discord-hybrid-sharding\src\Core\Cluster.js:154:24)
    at Object.onceWrapper (node:events:628:26)
    at Cluster.emit (node:events:513:28)
    at Cluster._handleExit (C:\Users\wibe0\OneDrive\桌面\blackcat\node_modules\discord-hybrid-sharding\src\Core\Cluster.js:278:54)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on Cluster instance at:
    at C:\Users\wibe0\OneDrive\桌面\blackcat\node_modules\discord-hybrid-sharding\src\Core\Cluster.js:299:98
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### 使用的軟體套件管理系統

npm

### 作業系統

Windows

**Comment by wolf-yuan-6115** [comment]
由於 https://github.com/blackcatbot/blackcat/issues/303 ，此錯誤才才會發生
