### ISSUE TITLE
新增24/7、音樂部分按鈕

### ISSUE THREAD

**Issue by wibe01204** [blackcatbot/blackcat#305]
### 你希望有什麽功能？

24/7功能，音樂按鈕的部分想要在下方新增循環撥放跟隨機撥放
例圖:
![image](https://user-images.githubusercontent.com/90883053/190959643-88cd84af-47c8-4645-83bd-5add07d20678.png)

### 為什麼？

有24/7功能的話可以讓機器人不會反覆進出頻道
新增循環撥放、隨機撥放按鈕可以有更直觀方便的使用體驗

還請參考~

**Comment by wolf-yuan-6115** [comment]
新增隨機播放與重複播放應該還可以

24/7我需要再研究一下

**Comment by wibe01204** [comment]
@wolf-yuan-6115 好的 麻煩了 感謝~

**Comment by wibe01204** [comment]
對了 如果單曲循環跟歌單循環的按鈕寫在一起應該不錯
昨天自己稍微研究了一下 不過還是有點看不懂😢

**Comment by wolf-yuan-6115** [comment]
> 對了 如果單曲循環跟歌單循環的按鈕寫在一起應該不錯
> 昨天自己稍微研究了一下 不過還是有點看不懂😢

我通常會寫在一起，反正也不是很難
