### ISSUE TITLE
無法運行Cannot read properties of undefined (reading 'defaultIcon')

### ISSUE THREAD

**Issue by huskyy8y8** [blackcatbot/blackcat#323]
### 目前行為

使用windows及ubuntu都嘗試過了但還是獲得如下報錯

### 終端輸出

![image](https://user-images.githubusercontent.com/69740916/198840142-30fee154-57f2-40d4-849d-9a7759945538.png)

### 使用的軟體套件管理系統

npm

### 作業系統

Windows

**Comment by wolf-yuan-6115** [comment]
https://github.com/blackcatbot/blackcat/issues/308

**Comment by huskyy8y8** [comment]
我看官方好像有建議使用play-dl2

[https://github.com/play-dl/play-dl/pull/328](url)

**Comment by wolf-yuan-6115** [comment]
已修復 https://github.com/blackcatbot/blackcat/commit/549aea0b85eb9c68dd2c7da9798c2732c17392dd
