### ISSUE TITLE
Error: Cannot play audio as no valid encryption package is installed.

### ISSUE THREAD

**Issue by huskyy8y8** [blackcatbot/blackcat#324]
### 目前行為

我依照提示安裝了
`Install sodium, libsodium-wrappers, or tweetnacl.`
但使用時還是顯示如下報錯

### 終端輸出

![image](https://user-images.githubusercontent.com/69740916/198847459-88f458f3-61a3-4bae-bcf0-8cea9bec43df.png)

### 使用的軟體套件管理系統

yarn

### 作業系統

Windows

**Comment by wolf-yuan-6115** [comment]
正常來說執行安裝指令時或安裝 `sodium-native`
請嘗試執行以下指令
```bash
yarn add @discordjs/voice@latest sodium-native@latest
```

**Comment by huskyy8y8** [comment]
自己按照如上指令操作但還是獲得同樣的結果
![image](https://user-images.githubusercontent.com/69740916/198863719-a376b565-0125-4b6f-b5d8-f971fad7d31a.png)

![image](https://user-images.githubusercontent.com/69740916/198863742-631e7596-a37b-4a7b-81f6-5970d2c19f4a.png)

**Comment by wolf-yuan-6115** [comment]
@huskyy8y8 請嘗試安裝 libsodium-wrappers

**Comment by Gary50613** [comment]
請問在安裝時有出現任何錯誤嗎？如 Visual Studio 等錯誤

照理來說它會自動安裝 `sodium`

**Comment by huskyy8y8** [comment]
有出現缺少 Visual Studio 2015的錯誤，有自己補上去了
不知道是不是windows的問題

**Comment by Gary50613** [comment]
那再重新 `yarn` 一次看看

**Comment by wolf-yuan-6115** [comment]
@huskyy8y8 請問使用Ubuntu時會出現這個錯誤嗎？

**Comment by TNTsky** [comment]
在Windows跟Ubuntu都會出現這個錯誤
發現疑似@discordjs/voice@0.13.0的問題
裝回0.11.0就正常了

**Comment by wolf-yuan-6115** [comment]
已經被修復，但是他們還沒有釋出新的更新 https://github.com/discordjs/discord.js/issues/8740
